### ISSUE TITLE
Pushing copies of notebooks to Google drive

### ISSUE THREAD

**Issue by hyanwong** [ebp-nor/GARG#3]
Now that we have code to allow the notebooks to work on both JupyyerLite and Colab, I guess it would be useful to set up an action to push (overwrite) copies of the notebooks in `jlite/content/*.ipynb` to the GARG_workshop drive (within the Notebooks directory). We can do this by hand easily enough too, so may not be worth automating.

We should also check that we push the latest `ARG_workshop.py` and `quiz.yaml` files to `Notebooks/python_modules` too.

**Comment by percyfal** [comment]
I don't think we need to. The links to the notebooks are e.g., https://colab.research.google.com/github/ebp-nor/GARG/blob/main/jlite/content/Day1-A-tskit_and_genealogies.ipynb, so it should pick up the notebook from the github repo.
